# Install and configure Kubernetes on the Worker nodes
---
- name: Install and configure Kubernetes on the Master
  hosts: all
  become: yes
  vars:
    kube_apiserver_address: "10.0.10.20:6443"
    token_ca_cert_hash: "sha256:53c99b7f133a757e97eccd797a9202d9924f84487d07097d42fb8888f568c8ef"
    token_bootkube: "8eoec0.wnt83yrwd72wx637"
    
- name: Install Docker on node
  import_playbook: ../install_docker.yml

- name: Install Kubeadm on node
  import_playbook: ../install_kubernetes.yml

- name: Configure Join to the cluster
  import_playbook: ../configure_node.yml