# Install and configure Kubernetes on the Worker nodes
---
- include: ../install_docker.yml 

- include: ../install_kubernetes.yml

- include: ../configure_node.yml token_bootkube="8eoec0.wnt83yrwd72wx637" kube_apiserver_address="10.0.10.20:6443" token_ca_cert_hash="sha256:53c99b7f133a757e97eccd797a9202d9924f84487d07097d42fb8888f568c8ef"