# Install and configure Kubernetes on the Master
---
- name: Install and configure Kubernetes on the Master
  hosts: all
  become: yes
- name: Install Docker on Master
  import_playbook: ../install_docker.yml

- name: Install Kubeadm on Master
  import_playbook: ../install_kubernetes.yml

- name: Configure Kubeadm Master
  import_playbook: ../configure_master.yml