# configure_kubeadm.yml
---
- name: Configure kubeadm
  hosts: all
  become: yes
  tasks:
    - block: 
        - name: Desativar swap
          command: swapoff -a
          when: ansible_swaptotal_mb > 0
        
        - name: Kubeadm init
          command: kubeadm init --ignore-preflight-errors=all
          register: kubeadm_config
        
        - debug: var=kubeadm_config.stdout_lines
        
        - name: .kube directory creation
          ansible.builtin.file:
            path: $HOME/.kube

        - name: Copy kube config
          ansible.builtin.copy:
            src: /etc/kubernetes/admin.conf
            dest: $HOME/.kube/config

        - name: Change kubeconfig file permission
          file:
            path: $HOME/.kube/config 
            owner: ubuntu
        
        - name: install Pod network
            shell: kubectl apply -f kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml >> pod_network_setup.log
            args:
              chdir: $HOME
              creates: pod_network_setup.log        
        