all:
  children:
    k8s:
      hosts:
        k8s_master:
          ansible_host: 10.0.10.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /ansible_recipes/test.pem
        k8s_node:
          ansible_host: 10.0.10.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /ansible_recipes/test.pem
    gitlabCICD:
      hosts:
        gitlabCICD_host:
          ansible_host: 10.0.20.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /ansible_recipes/test.pem
    argoCD:
      hosts:
        argoCD_host:
          ansible_host: 10.0.30.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /ansible_recipes/test.pem
    prometheus:
      hosts:
        prometheus_host:
          ansible_host: 10.0.50.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /ansible_recipes/test.pem