---
- name: Install and configure Kubernetes on the Worker nodes
  hosts: all
  become: yes
  vars:
    kube_apiserver_address: "10.0.10.10:6443"
    token_bootkube: "mrqktl.ou3ml8nd6a9oiyw8"
    token_ca_cert_hash: "sha256:82329bf42b7ee306d7647cb2d76049344160c6b005b06b5676342fdc988a4882"
  roles:
    - role: install_docker
    - role: install_kubernetes
    - role: configure_node