# install_docker.yml
---
- name: Install Docker
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: update
      apt:
        update_cache: yes

    - name: Install certificate
      apt:
        name: ca-certificates
        state: present
    
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: keyrings
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

    - name: Permission to docker.asc
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'  

    - name: Add Docker repository
      become: yes
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"       

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: present
    
    - name: Install docker-ce-cli
      apt:
        name: docker-ce-cli
        state: present

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present

    - name: Install docker-buildx-plugin
      apt:
        name: docker-buildx-plugin
        state: present

    - name: Install docker-compose-plugin
      apt:
        name: docker-compose-plugin
        state: present

    - name: Check docker version
      shell: docker --version
      register: docker_version

    - name: Playbook finished
      debug:
        msg: "Docker installed and configurated with the version: {{ docker_version.stdout }}"
      when: docker_version is defined and docker_version.stdout is defined