# install_docker.yml
---
- name: Install Docker
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Install certificate
      apt:
        name: ca-certificates
        state: present
    
    - name: Install prerequisite packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - ca-certificates
        - software-properties-common

    - name: Add Docker's GPG key
      become: yes
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker repository entry
      become: yes
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        create: yes

    - name: Update package lists
      become: yes
      apt:
        update_cache: yes

    - name: Check Docker CE package policy
      become: yes
      apt:
        name: docker-ce
        cache_policy: yes

    - name: Install Docker CE
      become: yes
      apt:
        name: docker-ce
        state: present

    - name: Check Docker service status
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes