# Install and configure Kubernetes on the Master
---
- name: Install and configure Kubernetes on the Worker nodes
  hosts: all
  become: yes
  roles:
    - role: install_docker
    - role: install_kubernetes
    - role: configure_master