---
- name: Install and configure Kubernetes on the Master
  hosts: all
  become: yes
  vars:
    cluster_ip: "10.10.0.0/16"
  roles:
    - role: install_docker
    - role: install_kubernetes
    - role: configure_master