# Install_kubernetes.yml
---
- name: Install kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
      register: update_cache_result  
        
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result
    
    - block:
        - name: Install prerequisite packages
          apt:
            name: "{{ item }}"
            state: present
          loop:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
          register: install_prereqs_result

        - name: Ensure /etc/apt/keyrings directory exists
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'       

        - name: Download the Kubernetes APT key
          ansible.builtin.get_url:
            url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
            dest: /tmp/Release.key
            mode: '0644'

        - name: Dearmor the Kubernetes APT key
          ansible.builtin.command:
            cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key
          args:
            creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

        - name: Remove the temporary APT key file
          ansible.builtin.file:
            path: /tmp/Release.key
            state: absent
        
        - name: Add Kubernetes repository entry manually
          shell: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          register: add_repo_result
        
        - name: Install kubeadm, kubectl and kubelet packages
          apt:
            name: "{{ item }}"
            state: present
          loop:
            - kubelet
            - kubeadm
            - kubectl
          register: install_kubeadm_kubelet_kubectl
        
        - name: Ensure kubelet service is enabled and started
          ansible.builtin.systemd:
            name: kubelet
            enabled: yes
            state: started
        