# Install and configure Kubernetes on the Worker nodes
---
- name: Install and configure Kubernetes on the Worker nodes
  hosts: all
  become: yes
  vars:
    token_bootkube: "8eoec0.wnt83yrwd72wx637"
    kube_apiserver_address: "10.0.10.20:6443"
    token_ca_cert_hash: "sha256:53c99b7f133a757e97eccd797a9202d9924f84487d07097d42fb8888f568c8ef"
  roles:
    - role: /ansible_recipes/install_docker/tasks/main.yml
    - role: /ansible_recipes/install_kubernetes/tasks/main.yml
    - role: /ansible_recipes/configure_node/tasks/main.yml