---
- name: Install and configure Kubernetes on the Worker nodes
  hosts: all
  become: yes
  vars_prompt:
    - name: "kube_apiserver_address"
      prompt: "Please enter the value for kube_apiserver_address"
      private: no
    - name: "token_bootkube"
      prompt: "Please enter the value for token_bootkube"
      private: no
    - name: "token_ca_cert_hash"
      prompt: "Please enter the value for token_ca_cert_hash"
      private: no
  roles:
    - role: install_docker
    - role: install_kubernetes
    - role: configure_node