# install_docker.yml
---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - ca-certificates
        - software-properties-common

    - name: Add Docker's GPG key
      shell: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker repository
      shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      args:
        warn: false

    - name: Update package lists again
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Check Docker service status
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker version
      shell: docker --version
      register: docker_version

    - name: Playbook finished
      debug:
        msg: "Docker installed and configured with the version: {{ docker_version.stdout }}"
      when: docker_version is defined and docker_version.stdout is defined