---
- name: Set a valid hostname variable
  set_fact:
    valid_hostname: "{{ inventory_hostname | replace('_', '-') }}"

- name: Set hostname to valid inventory hostname (if needed)
  hostname:
    name: "{{ valid_hostname }}"
  when: ansible_hostname != valid_hostname

- name: Disable swap
  command: swapoff -a

- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr={{ cluster_ip }}--ignore-preflight-errors=all
  register: kubeadm_output
  ignore_errors: yes

- debug:
    var: kubeadm_output.stdout_lines

- name: Set up kubectl for the current user
  command: "{{ item }}"
  loop:
    - "mkdir -p $HOME/.kube"
    - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: Change kubeconfig file permission
  file:
    path: $HOME/.kube/config 
    owner: ubuntu

- name: Install Calico network plugin
  command: "{{ item }}"
  loop:
    - "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml"
    - "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml"
  when: kubeadm_output is succeeded
