---
- name: Update package lists after adding Kubernetes repository
  apt:
    update_cache: yes

- name: Install helm using online script
  shell: sudo curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sudo bash
  register: helm_instalation
