---
- name: Set hostname to node (if needed)
  hostname:
    name: node
  when: ansible_hostname != "node"

- name: Add node to the cluster
  command: kubeadm join {{ kube_apiserver_address }} --token {{ token_bootkube }} --node-name node --discovery-token-ca-cert-hash {{ token_ca_cert_hash }}
  args:
    chdir: /etc/kubernetes
  become_user: root

- name: kubectl taints
  command: 'kubectl taints nodes node node-role.kubernetes.io/worker: "NoSchedule" --overwrite'